// Datos mock para testing de UI sin backend

export const mockOfertas = [
  {
    id: '1',
    titulo: 'Guardia de seguridad para evento',
    categoria: 'Guardia',
    descripcion: 'Se busca guardia de seguridad para evento corporativo',
    region: 'RM',
    comuna: 'Santiago Centro',
    remuneration: { monto: 500000, forma_pago: 'mes' },
    jornada: 'full_time',
    tipo_contrato: 'PLAZO_FIJO',
    estado: 'ABIERTA',
    created_at: '2024-01-15T10:00:00Z',
    _count: { postulaciones: 12 },
  },
  {
    id: '2',
    titulo: 'Conserje para edificio residencial',
    categoria: 'Conserje',
    descripcion: 'Se necesita conserje para edificio de departamentos',
    region: 'RM',
    comuna: 'Providencia',
    remuneration: { monto: 450000, forma_pago: 'mes' },
    jornada: 'full_time',
    tipo_contrato: 'PLAZO_FIJO',
    estado: 'ABIERTA',
    created_at: '2024-01-14T08:00:00Z',
    _count: { postulaciones: 5 },
  },
  {
    id: '3',
    titulo: 'Personal de aseo para oficina',
    categoria: 'Aseo',
    descripcion: 'Se necesita personal de limpieza para oficina',
    region: 'V',
    comuna: 'Viña del Mar',
    remuneration: { monto: 350000, forma_pago: 'mes' },
    jornada: 'parcial',
    tipo_contrato: 'HONORARIOS',
    estado: 'CON_CANDIDATOS',
    created_at: '2024-01-10T14:00:00Z',
    _count: { postulaciones: 8 },
  },
  {
    id: '4',
    titulo: 'Temporero para temporada de cosecha',
    categoria: 'Temporero',
    descripcion: 'Trabajo temporal para temporada de cosecha',
    region: 'VI',
    comuna: 'Rancagua',
    remuneration: { monto: 25000, forma_pago: 'jornada' },
    jornada: 'full_time',
    tipo_contrato: 'PLAZO_FIJO',
    estado: 'CERRADA',
    created_at: '2024-01-05T09:00:00Z',
    _count: { postulaciones: 20 },
  },
]

export const mockTrabajadores = [
  {
    id: '1',
    nombre_completo: 'Juan Pérez González',
    rut: '12.345.678-5',
    telefono: '+56912345678',
    region: 'RM',
    comuna: 'Santiago Centro',
    movilizacion_propia: true,
    disponibilidad: { dias: ['L', 'M', 'X', 'J', 'V'], horarios: ['full_time'] },
    pretension_renta: { min: 400000, max: 600000, tipo: 'mes' },
    certificaciones: ['OS10', 'Primeros Auxilios'],
    experiencia: [
      { empresa: 'Seguridad ABC', cargo: 'Guardia', periodo: '2020-2023', descripcion: 'Guardia de seguridad' },
    ],
  },
  {
    id: '2',
    nombre_completo: 'María González López',
    rut: '13.456.789-2',
    telefono: '+56923456789',
    region: 'RM',
    comuna: 'Providencia',
    movilizacion_propia: true,
    disponibilidad: { dias: ['L', 'M', 'X', 'J', 'V'], horarios: ['parcial'] },
    pretension_renta: { min: 300000, max: 450000, tipo: 'mes' },
    certificaciones: ['OS10'],
    experiencia: [
      { empresa: 'Edificio Plaza', cargo: 'Conserje', periodo: '2019-2023', descripcion: 'Conserje y aseo' },
    ],
  },
  {
    id: '3',
    nombre_completo: 'Carlos Rodríguez Silva',
    rut: '14.567.890-8',
    telefono: '+56934567890',
    region: 'V',
    comuna: 'Viña del Mar',
    movilizacion_propia: false,
    disponibilidad: { dias: ['L', 'M', 'X', 'J', 'V', 'S'], horarios: ['full_time', 'horas'] },
    pretension_renta: { min: 350000, max: 500000, tipo: 'mes' },
    certificaciones: ['SEC'],
    experiencia: [
      { empresa: 'Electricista SPA', cargo: 'Electricista', periodo: '2018-2023', descripcion: 'Instalaciones eléctricas' },
    ],
  },
  {
    id: '4',
    nombre_completo: 'Ana Martínez Fernández',
    rut: '15.678.901-4',
    telefono: '+56945678901',
    region: 'RM',
    comuna: 'Las Condes',
    movilizacion_propia: true,
    disponibilidad: { dias: ['L', 'M', 'X', 'J', 'V'], horarios: ['full_time'] },
    pretension_renta: { min: 500000, max: 700000, tipo: 'mes' },
    certificaciones: ['OS10', 'Primeros Auxilios', 'Manipulación de Alimentos'],
    experiencia: [
      { empresa: 'Hotel Grand', cargo: 'Encargada de aseo', periodo: '2020-2023', descripcion: 'Supervisión de aseo' },
    ],
  },
]

export const mockPostulaciones = [
  {
    id: '1',
    oferta_id: '1',
    trabajador_id: '1',
    score_match: 85,
    mensaje: 'Tengo experiencia en eventos corporativos',
    estado: 'PENDIENTE',
    created_at: '2024-01-16T10:00:00Z',
    trabajador: mockTrabajadores[0],
  },
  {
    id: '2',
    oferta_id: '1',
    trabajador_id: '2',
    score_match: 72,
    mensaje: 'Disponible inmediatamente',
    estado: 'PENDIENTE',
    created_at: '2024-01-16T11:00:00Z',
    trabajador: mockTrabajadores[1],
  },
]